<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $permissions = [
            'dashboard.view',
            'users.view',
            'users.create',
            'users.edit',
            'users.delete',
            'users.restore',
            'users.change-password',
            'users.assign-roles',
            'roles.view',
            'roles.create',
            'roles.edit',
            'roles.delete',
            'roles.assign-permissions',
            'permissions.view',
            'permissions.create',
            'permissions.edit',
            'permissions.delete',
            'companies.view',
            'companies.create',
            'companies.update',
            'companies.delete',
            'branches.view',
            'branches.create',
            'branches.update',
            'branches.delete',
            'warehouses.view',
            'warehouses.create',
            'warehouses.update',
            'warehouses.delete',
            'point-of-sales.view',
            'point-of-sales.create',
            'point-of-sales.update',
            'point-of-sales.delete',
            'suppliers.view',
            'suppliers.create',
            'suppliers.update',
            'suppliers.delete',
            'products.view',
            'products.create',
            'products.edit',
            'products.update',
            'products.delete',
            'product-presentations.view',
            'product-presentations.create',
            'product-presentations.update',
            'product-presentations.delete',
            'categories.view',
            'categories.create',
            'categories.edit',
            'categories.update',
            'categories.delete',
            'measurement-units.view',
            'measurement-units.create',
            'measurement-units.update',
            'measurement-units.delete',
            'payment-methods.view',
            'payment-methods.create',
            'payment-methods.update',
            'payment-methods.delete',
            'inventory.view',
            'inventory.movements',
            'purchases.view',
            'purchases.create',
            'purchases.void',
            'sales.view',
            'sales.create',
            'sales.void',
            'pos.access',
            'reports.view',
            'audits.view',
            'roles.manage',
            'users.manage',
        ];

        foreach ($permissions as $permission) {
            Permission::findOrCreate($permission);
        }

        $allPermissions = Permission::pluck('name')->all();

        Role::findOrCreate('admin')->syncPermissions($allPermissions);
        Role::findOrCreate('super_admin')->syncPermissions($allPermissions);

        Role::findOrCreate('manager')->syncPermissions([
            'dashboard.view',
            'users.view',
            'companies.view',
            'companies.create',
            'companies.update',
            'branches.view',
            'branches.create',
            'branches.update',
            'warehouses.view',
            'warehouses.create',
            'warehouses.update',
            'point-of-sales.view',
            'point-of-sales.create',
            'point-of-sales.update',
            'suppliers.view',
            'products.view',
            'products.create',
            'products.edit',
            'products.update',
            'product-presentations.view',
            'product-presentations.create',
            'product-presentations.update',
            'categories.view',
            'categories.create',
            'categories.edit',
            'categories.update',
            'measurement-units.view',
            'measurement-units.create',
            'measurement-units.update',
            'payment-methods.view',
            'payment-methods.create',
            'payment-methods.update',
            'inventory.view',
            'purchases.view',
            'purchases.create',
            'purchases.void',
            'sales.view',
            'sales.void',
            'reports.view',
        ]);

        Role::findOrCreate('cashier')->syncPermissions([
            'dashboard.view',
            'companies.view',
            'branches.view',
            'warehouses.view',
            'point-of-sales.view',
            'products.view',
            'product-presentations.view',
            'categories.view',
            'measurement-units.view',
            'payment-methods.view',
            'sales.view',
            'sales.create',
            'pos.access',
        ]);

        Role::findOrCreate('warehouse')->syncPermissions([
            'dashboard.view',
            'companies.view',
            'branches.view',
            'warehouses.view',
            'warehouses.create',
            'warehouses.update',
            'point-of-sales.view',
            'point-of-sales.create',
            'point-of-sales.update',
            'suppliers.view',
            'products.view',
            'products.create',
            'products.edit',
            'products.update',
            'product-presentations.view',
            'product-presentations.create',
            'product-presentations.update',
            'categories.view',
            'measurement-units.view',
            'inventory.view',
            'inventory.movements',
            'purchases.view',
            'purchases.create',
        ]);

        Role::findOrCreate('inventory_manager')->syncPermissions([
            'dashboard.view',
            'companies.view',
            'branches.view',
            'branches.create',
            'branches.update',
            'warehouses.view',
            'warehouses.create',
            'warehouses.update',
            'point-of-sales.view',
            'point-of-sales.create',
            'point-of-sales.update',
            'suppliers.view',
            'categories.view',
            'categories.create',
            'categories.edit',
            'categories.update',
            'measurement-units.view',
            'measurement-units.create',
            'measurement-units.update',
            'products.view',
            'products.create',
            'products.edit',
            'products.update',
            'product-presentations.view',
            'product-presentations.create',
            'product-presentations.update',
            'inventory.view',
            'inventory.movements',
            'reports.view',
        ]);

        Role::findOrCreate('viewer')->syncPermissions([
            'dashboard.view',
            'companies.view',
            'branches.view',
            'warehouses.view',
            'point-of-sales.view',
            'categories.view',
            'measurement-units.view',
            'products.view',
            'reports.view',
        ]);

        app()[PermissionRegistrar::class]->forgetCachedPermissions();
    }
}
