<div class="row g-3" data-personnel-form data-lookup-url="{{ route('personnel.lookup') }}" data-current-personnel-id="{{ $personnel->id ?? '' }}">
 <div class="col-12"><label class="form-label" for="personnel-identity-document">CI</label><input class="form-control" id="personnel-identity-document" name="identity_document" value="{{ old('identity_document',$personnel->identity_document ?? '') }}" maxlength="30" required data-personnel-ci><div class="form-text">Ingrese primero el CI para verificar si ya está registrado en esta empresa.</div><div class="invalid-feedback" data-error-for="identity_document"></div></div>
 <div class="col-12 d-none" data-personnel-existing-alert><div class="alert alert-warning mb-0"><div class="d-flex flex-wrap align-items-center justify-content-between gap-2"><div><strong>Personal ya registrado</strong><div data-personnel-existing-message></div></div><div class="d-flex gap-2" data-personnel-existing-actions></div></div></div></div>
 <div class="col-md-4"><label class="form-label">Nombres</label><input class="form-control" name="first_name" value="{{ old('first_name',$personnel->first_name ?? '') }}" required></div>
 <div class="col-md-4"><label class="form-label">Apellido paterno</label><input class="form-control" name="paternal_surname" value="{{ old('paternal_surname',$personnel->paternal_surname ?? '') }}" required></div>
 <div class="col-md-4"><label class="form-label">Apellido materno</label><input class="form-control" name="maternal_surname" value="{{ old('maternal_surname',$personnel->maternal_surname ?? '') }}"></div>
 <div class="col-md-4"><label class="form-label">Fecha de nacimiento</label><input class="form-control" type="date" name="birth_date" value="{{ old('birth_date',isset($personnel) ? $personnel->birth_date?->format('Y-m-d') : '') }}"></div>
 <div class="col-md-4"><label class="form-label required">Teléfono</label><input class="form-control" name="phone" value="{{ old('phone',$personnel->phone ?? '') }}" maxlength="30" required></div>
 <div class="col-md-6"><label class="form-label required">Correo</label><input class="form-control" type="email" name="email" value="{{ old('email',$personnel->email ?? '') }}" maxlength="255" required></div>
 <div class="col-md-6"><label class="form-label">Área / Cargo</label><select class="form-select" name="position_id" required><option value="">Seleccione</option>@foreach($positions->groupBy(fn($p)=>$p->area->name) as $area=>$items)<optgroup label="{{ $area }}">@foreach($items as $position)<option value="{{ $position->id }}" @selected((int)old('position_id',$personnel->position_id ?? 0)===$position->id)>{{ $position->name }}</option>@endforeach</optgroup>@endforeach</select></div>
 <div class="col-md-6"><label class="form-label" for="personnel-campus">Sede</label><select class="form-select @error('campus_id') is-invalid @enderror" id="personnel-campus" name="campus_id"><option value="">Sin sede asignada</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected((int)old('campus_id',$personnel->campus_id ?? 0)===$campus->id)>{{ $campus->name }} · {{ $campus->code }}</option>@endforeach</select>@error('campus_id')<div class="invalid-feedback">{{ $message }}</div>@enderror @if($campuses->isEmpty())<div class="form-text">Registra una sede desde Organización → Sedes para poder asignarla.</div>@endif</div>
 <div class="col-12"><input type="hidden" name="is_active" value="0"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$personnel->is_active ?? true))><span class="form-check-label">Personal activo</span></label></div>
</div>
@if($errors->any())<div class="alert alert-danger mt-3"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
